name: protein-study
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch
  - pip
  - pip:
    - fair-esm
    - biopython
    - transformers
